2025-09-14T11:22:00.395+0530	ERROR	test/pg_services_test.go:136	src :SyncSummary error while fetching from external repo: 	{"error": "external service down"}
